server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true

security:
  jwt:
    access-token:
      validity-seconds: 3600
    refresh-token:
      validity-seconds: 1209600

springdoc:
  swagger-ui:
    enabled: false  # Swagger UI 비활성화
  api-docs:
    enabled: false # OpenAPI 문서 생성 비활성화