spring:
  application:
    name: myplatform-api
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    access-token:
      secret-key: ${JWT_SECRET:access-token-secret-key-string-value}
      issuer: https://api.myplatform.aaws.page
    refresh-token:
      secret-key: ${JWT_SECRET:access-token-secret-key-string-value}
      issuer: https://api.myplatform.aaws.page